### ISSUE TITLE
Request for model weights on Ecoset

### ISSUE THREAD

**Issue by LuZeking** [neuroailab/TDANN#1]
Hi,

I am very impressed by your work and I would like to explore it further. Could you please share the model weights that you trained on Ecoset? I would appreciate your generosity and cooperation :)!

**Comment by eshedmargalit** [comment]
Thank you! I just uploaded the model weights for the Ecoset-trained model, you can find it here in the OSF repository: [https://osf.io/64qv3/](https://osf.io/64qv3/) under `tdann_data > tdann > checkpoints > by_training_data > simclr_ecoset`
