### ISSUE TITLE
Questions about training time

### ISSUE THREAD

**Issue by Dongze-Li** [neuroailab/TDANN#7]
Hi, sorry to bother you. Would you mind giving a general reference for the training time. For example, how long does it take with how many specific GPUs to train say 200 epochs?

I just want to check if our training time are on the right track.

Thank you very much!

**Comment by eshedmargalit** [comment]
@Dongze-Li You should expect about 1-2 weeks of training time per model distributed over about 48GB of GPU memory. We trained on different sets of cards, but generally those times should be accurate for 4 cards of 12GB/ea or 2 cards of 24GB/ea. Hope that helps!

I also apologize for the delayed reply; I'll try to monitor this repository more closely. Feel free to tag me directly (@eshedmargalit) in the future if I haven't seen something.
