### ISSUE TITLE
what does a model unit？

### ISSUE THREAD

**Issue by xxyh1993** [neuroailab/TDANN#8]
This question always confuses me. I know there are share weights and representations in CNN, but I really don't understand what a model unit represent. Could you explain this? Thank you for your help very much.

**Comment by eshedmargalit** [comment]
I think this is a deep question with many plausible answers, so I'll share how I think about things in the context of this TDANN project.

A neural network is defined by a set of weights and a computation graph, which is a structured collection of operations (multiply, add, nonlinearity, etc) that depend on the weights. When you run an input "forward" through the neural network, each operation produces a set of activations. For example, applying a convolutional layer with 16 8x8 filters to a 224 x 224 x 3 input image with stride = 2 will produce 16 * 109 * 109 = 109,096 values. I would think of each of these 109k activations as a "model unit". They are like neurons whose firing rates (the values computed) depend on the input (`images`) and the synaptic weights (`layer.weight`, which has shape [16, 3, 8, 8]).

```python
import torch

images = torch.rand(1, 3, 224, 224)
layer = torch.nn.Conv2d(in_channels=3, out_channels=16, kernel_size=8, stride=2)

outputs = layer(images)
print(outputs.shape) # will print [1, 16, 109, 109]
```

In the TDANN project, we think of this layer as having 109k model units, and we analyze it accordingly. Let me know if you have other questions about the project.

**Comment by xxyh1993** [comment]
> I think this is a deep question with many plausible answers, so I'll share how I think about things in the context of this TDANN project.
> 
> A neural network is defined by a set of weights and a computation graph, which is a structured collection of operations (multiply, add, nonlinearity, etc) that depend on the weights. When you run an input "forward" through the neural network, each operation produces a set of activations. For example, applying a convolutional layer with 16 8x8 filters to a 224 x 224 x 3 input image with stride = 2 will produce 16 * 109 * 109 = 109,096 values. I would think of each of these 109k activations as a "model unit". They are like neurons whose firing rates (the values computed) depend on the input (`images`) and the synaptic weights (`layer.weight`, which has shape [16, 3, 8, 8]).
> 
> ```python
> import torch
> 
> images = torch.rand(1, 3, 224, 224)
> layer = torch.nn.Conv2d(in_channels=3, out_channels=16, kernel_size=8, stride=2)
> 
> outputs = layer(images)
> print(outputs.shape) # will print [1, 16, 109, 109]
> ```
> 
> In the TDANN project, we think of this layer as having 109k model units, and we analyze it accordingly. Let me know if you have other questions about the project.

I get it now, thanks!
